# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e876b0ee74931fa7d5c239583a6e24898502ee5fa30dfb4adaf5d8cdbcca4f7dd00e7916020d8929c788cf8ceb5627076263da3c3ee3b87925944f17f3cbc78

test:
  secret_key_base: 795b13ca3ef8873a9efd333b2f5bc807a6bc4710a0897c85fbdf5bbadfaaf9c003daa7031fc78ebd47245e4bdcf6ac977ca2c372052928ce1dade6d525ae933f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
